<?php

/**
 * @file
 * Contains hook implementations for the Tome Forms module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\tome_static\StaticGeneratorInterface;

/**
 * Implements hook_help().
 */
function tome_forms_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.tome_forms':
      return t("TODO: Create admin help text.");

    // OPTIONAL: Add additional cases for other paths that should display
    // help text.
  }
}

/**
 * Implements hook_form_alter().
 */
function tome_forms_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter forms that are configured to be exported as Tome static forms so that
  // they are submitted to the form handler PHP script.
  // Only act within a Tome export request.
  $request = \Drupal::request();
  if ($request->attributes->get(StaticGeneratorInterface::REQUEST_KEY) != StaticGeneratorInterface::REQUEST_KEY) {
    // return;
  }

  $tome_form_storage = \Drupal::service('entity_type.manager')->getStorage('tome_form');
  $tome_form_entities = $tome_form_storage->loadMultiple();
  /** @var \Drupal\tome_forms\Entity\TomeFormInterface */
  foreach ($tome_form_entities as $tome_form_entity_id => $tome_form_entity) {
    // Only act on the Tome form entity for this form, if one exists.
    if ($tome_form_entity->getFormId() != $form_id) {
      continue;
    }

    // Hand over to the Tome form entity to make alterations.
    $tome_form_entity->formAlter($form, $form_state);

    // Set the form action to the form handler script for this Tome form
    // entity and ensure the form method is POST. Form handler plugins that
    // don't use a local script should make their own changes in formAlter().
    if ($tome_form_entity->useLocalScript()) {
      $form['#action'] = $tome_form_entity->getFormHandlerExportedScriptPath();
      $form['#method'] = 'post';
    }

    // Only one Tome form entity should act on a single form, so we're done.
    return;
  }
}
