'tome_forms.tome_form.*':
  type: config_entity
  label: 'Tome Form'
  mapping:
    id:
      type: text
      label: 'Machine name'
    label:
      type: label
      label: Name
    form_id:
      type: string
      label: 'Form Id'
    paths:
      type: string
      label: 'Paths'
    form_handler_id:
      type: string
      label: 'Form handler plugin ID'
    form_handler_config:
      # @todo expand!
      type: ignore
      label: 'Form handler plugin configuration'
